App {
	name: "NoCodeBrowser"
	icon: "icon.png"
	id: "at.crowdware.nocodebrowser"
	smlVersion: "1.1"

  Theme {
    primary: "#FF0C8CE9"
    onPrimary: "#FFFFFF"
    primaryContainer: "#FFDDB3"
    onPrimaryContainer: "#291800"
    secondary: "#6F5B40"
    onSecondary: "#FFFFFF"
    secondaryContainer: "#FBDEBC"
    onSecondaryContainer: "#271904"
    tertiary: "#51643F"
    onTertiary: "#FFFFFF"
    tertiaryContainer: "#D4EABB"
    onTertiaryContainer: "#102004"
    error: "#BA1A1A"
    errorContainer: "#FFDAD6"
    onError: "#FFFFFF"
    onErrorContainer: "#410002"
    background: "#FFFBFF"
    onBackground: "#1F1B16"
    surface: "#FFFBFF"
    onSurface: "#1F1B16"
    surfaceVariant: "#F0E0CF"
    onSurfaceVariant: "#4F4539"
    outline: "#817567"
    inverseOnSurface: "#F9EFE7"
    inverseSurface: "#34302A"
    inversePrimary: "#FFB951"
    surfaceTint: "#825500"
    utlineVariant: "#D3C4B4"
    scrim: "#000000"
  }
}